{% set name = "voyageai" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/voyageai-{{ version }}.tar.gz
  sha256: 93c6bd519e26ecb41ba5ebd020788fbc0d78df2f923138faa03543fe711b0ee5
  patches:
    - pyproject.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <3.13,>=3.9
    - poetry-core
    - pip
  run:
    - pillow
    - pydantic >=1.10.8
    - tokenizers >=0.14.0
    - python <3.13,>=3.9
    - requests
    - aiohttp
    - tenacity
    - numpy
    - aiolimiter

test:
  imports:
    - voyageai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.voyageai.com
  summary: Vectorize your data to gear up your AI stack
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
