{% set name = "voyageai" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/voyageai-{{ version }}.tar.gz
  sha256: b2a526a31859f21782a309d8c40b69d8d8c499308ed96e2d81a6e1b952431c23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - langchain-text-splitters >=0.3.8
    - pillow
    - pydantic >=1.10.8
    - tokenizers >=0.14.0
    - python >={{ python_min }},<3.13
    - requests
    - aiohttp
    - tenacity
    - numpy
    - aiolimiter

test:
  imports:
    - voyageai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.voyageai.com
  summary: Vectorize your data to gear up your AI stack
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
