{% set name = "voyageai" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/voyageai-{{ version }}.tar.gz
  sha256: bd1b52d26179d91853cbd2a0e52dc95cb0d526760c6c830959e01eb5ff9eaa12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - pillow
    - pydantic >=1.10.8
    - tokenizers >=0.14.0
    - python >={{ python_min }},<3.13
    - requests
    - aiohttp
    - tenacity
    - numpy
    - aiolimiter

test:
  imports:
    - voyageai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.voyageai.com
  summary: Vectorize your data to gear up your AI stack
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
